---
title       : Operation Report
subtitle    : Presented By:- BAM&R Team
author      :
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight  # {highlight.js, prettify, highlight}
hitheme     : none      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
biglogo     : logo_delhivery.jpg
---

```{r , echo=FALSE}  
#Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre7')
#suppressPackageStartupMessages(library(rJava))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(xtable))
suppressPackageStartupMessages(library(reshape))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(googleVis))
#suppressPackageStartupMessages(library(ReporteRs))
#library('ReporteRs')
library('googleVis')
op<-options(gvis.plot.tag="chart")
```

```{r , echo=FALSE, warning=FALSE}

## Slide 3 - counts according to pt(Forward , Reverse , Cash)
zz_rep_13_10_3 = read.csv("~/R new1/zz-rep-13-10-3.csv")
zz_rep_13_10_3_op1 = zz_rep_13_10_3 %>%
  mutate(day_3=strftime(strptime(X_id.dl_date ,  "%j") , "%a"),
         date_3=strftime(strptime(X_id.dl_date ,  "%j") , "%D")
  )

slide_3_min_mon = zz_rep_13_10_3_op1 %>%
  filter(day_3=="Sun") %>%
  #group_by(dl_count) %>%
  summarize(min_mon = min(X_id.dl_date))

slide_3_min_mon = as.integer(slide_3_min_mon)

```

```{r , echo=FALSE, warning=FALSE}
cl_cs_pt_rep_13_10_3_zn = read.csv("~/R new1/cl-cs-pt-rep-13-10-3-zn.csv")
zz_rep_24_op1 = cl_cs_pt_rep_13_10_3_zn%>%
  filter(X_id..cnc %in% c("Delhi NCR" , "Bangalore" , "Hyderabad" , "Jaipur"
                            ,"Chennai"  , "Pune","Kolkata" , "Mumbai" , "Surat" , "Ahmedabad"))%>%
  filter(X_id.dl_pt %in% c("COD" , "Pre-paid")) %>%
  mutate(wkend_dt = (((as.numeric(X_id.dl_date) -slide_3_min_mon)%/%7)                     
                     *7)
         +as.integer(slide_3_min_mon)+6 , 
         Status = ifelse(X_id.dl_cs_ss %in% c("RTO" , "Returned") , "RTO" , "Other")
         )

zz_rep_24_op1$wkend_dt = as.character(zz_rep_24_op1$wkend_dt)

zz_rep_24_op1$wkend_dt = as.POSIXct(zz_rep_24_op1$wkend_dt , format="%j")

zz_rep_24_op2 = zz_rep_24_op1 %>%
  group_by(City = X_id..cnc , wkend_dt , Status)%>%
  summarize(sum = sum(as.numeric(dl_count)))%>%
  mutate(pct=100*sum/sum(sum)) %>%
  filter(Status=="RTO")


zz_rep_24_op3 = zz_rep_24_op2 %>%
  mutate(pct = paste(as.numeric(round(pct , 1)),"%")) %>%
    dcast(City~wkend_dt  ,value.var="pct")
  

zz_rep_24_op2 = zz_rep_24_op2 %>%
  group_by(City)%>%
  summarise(sum=sum(sum))%>%
  arrange(desc(sum))
  
zz_rep_24_op4 = inner_join(zz_rep_24_op2 , zz_rep_24_op3 , by="City")



######################################################

cl_cs_pt_rep_13_10_3_zn = read.csv("~/R new1/cl-cs-pt-rep-13-10-3-zn.csv")
zz_rep_24_op1 = cl_cs_pt_rep_13_10_3_zn%>%
  filter(X_id.cnc %in% c("Delhi NCR" , "Bangalore" , "Hyderabad" , "Jaipur"
                            ,"Chennai"  , "Pune","Kolkata" , "Mumbai" , "Surat" , "Ahmedabad"))%>%
  filter(X_id.dl_date>=slide_3_min_mon , X_id.dl_pt %in% c("COD")) %>%
  mutate(wkend_dt = (((as.numeric(X_id.dl_date) -slide_3_min_mon)%/%7)                     
                     *7)
         +as.integer(slide_3_min_mon)+6 , 
         Status = ifelse(X_id.dl_cs_ss %in% c("RTO" , "Returned") , "RTO" , "Other")
         )

zz_rep_24_op1$wkend_dt = as.character(zz_rep_24_op1$wkend_dt)

zz_rep_24_op1$wkend_dt = as.POSIXct(zz_rep_24_op1$wkend_dt , format="%j")

zz_rep_24_op2 = zz_rep_24_op1 %>%
  group_by(City = X_id.cnc , wkend_dt , Status)%>%
  summarize(sum = sum(as.numeric(dl_count)))%>%
  mutate(pct=100*sum/sum(sum)) %>%
  filter(Status=="RTO")


zz_rep_24_op3 = zz_rep_24_op2 %>%
  mutate(pct = paste(as.numeric(round(pct , 1)),"%")) %>%
    dcast(City~wkend_dt  ,value.var="pct")
  

zz_rep_24_op2 = zz_rep_24_op2 %>%
  group_by(City)%>%
  summarise(sum=sum(sum))%>%
  arrange(desc(sum))
  
zz_rep_24_op4_cod = inner_join(zz_rep_24_op2 , zz_rep_24_op3 , by="City")


zz_rep_24_op1 = cl_cs_pt_rep_13_10_3_zn%>%
  filter(X_id.cnc %in% c("Delhi NCR" , "Bangalore" , "Hyderabad" , "Jaipur"
                            ,"Chennai"  , "Pune","Kolkata" , "Mumbai" , "Surat" , "Ahmedabad"))%>%
  filter(X_id.dl_date>=slide_3_min_mon , X_id.dl_pt %in% c("COD")) %>%
  mutate(wkend_dt = (((as.numeric(X_id.dl_date) -slide_3_min_mon)%/%7)                     
                     *7)
         +as.integer(slide_3_min_mon)+6 , 
         Status = ifelse(X_id.dl_cs_ss %in% c("RTO" , "Returned") , "RTO" , "Other")
         )

zz_rep_24_op1$wkend_dt = as.character(zz_rep_24_op1$wkend_dt)

zz_rep_24_op1$wkend_dt = as.POSIXct(zz_rep_24_op1$wkend_dt , format="%j")

zz_rep_24_op2 = zz_rep_24_op1 %>%
  group_by(City = X_id.cnc , wkend_dt , Status)%>%
  summarize(sum = sum(as.numeric(dl_count)))%>%
  mutate(pct=100*sum/sum(sum)) %>%
  filter(Status=="RTO")


zz_rep_24_op3 = zz_rep_24_op2 %>%
  mutate(pct = paste(as.numeric(round(pct , 1)),"%")) %>%
    dcast(City~wkend_dt  ,value.var="pct")
  

zz_rep_24_op2 = zz_rep_24_op2 %>%
  group_by(City)%>%
  summarise(sum=sum(sum))%>%
  arrange(desc(sum))
  
zz_rep_24_op4_cod = inner_join(zz_rep_24_op2 , zz_rep_24_op3 , by="City")
```

## Lane Metrics - Returns/Reverse

---
# Lane Metrics - Return Rate
```{r ,echo=FALSE , results='asis'}
print(xtable(prettyNum(zz_rep_24_op4, big.interval = 3,big.mark=",")), 
      type="html"    , include.rownames=FALSE)
```


---
# Lane Metrics - Return Rate cod
```{r ,echo=FALSE , results='asis'}
print(xtable(prettyNum(zz_rep_24_op4_cod, big.interval = 3,big.mark=",")), 
      type="html"    , include.rownames=FALSE)
```
